version: 2
jobs:
  build:
    branches:
      only:
        - master
    working_directory: ~/tmp
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run: ssh -o StrictHostKeyChecking=no $DROPLET_USER@$DROPLET_IP 'cd /apps/appointments-frontend && git checkout master && git pull && npm run build && cp build/* -r /var/www/appointments/html'
